# -*- coding: utf-8 -*-
"""Advanced_Ai/ML_1st(PCA).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VDqEMFNEcsvDCcBuzHsv-EGP52uWjSXj
"""

import pandas as pd

df=pd.read_csv("/content/credit_card_fraud_10k.csv")

df.head()

df.tail()

df.shape

df.describe()

df.isnull().sum()

df_updated=df.drop(columns=["transaction_id","merchant_category",],errors='ignore')

df_updated.head()

df_updated["is_fraud"]=df_updated['is_fraud'].map({0:"fraud",1:"not fraud"})

y=df_updated["is_fraud"]
y

x=df_updated.drop(columns=["is_fraud"])
x

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

"""## Principal Component Analysis (PCA)

Before applying PCA, it's crucial to scale the data, as PCA is sensitive to the variance of the features. I will use `StandardScaler` to standardize the features, then apply PCA to reduce the dimensionality.
"""

x_test.shape

y_test.shape

from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
y_pred

from sklearn.metrics import accuracy_score,classification_report
score=accuracy_score(y_test,y_pred)
score

print(classification_report(y_pred,y_test))

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

import seaborn as sns

sns.heatmap(confusion_matrix(y_test,y_pred),annot=True)

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# Scale the features
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

# Apply PCA
pca = PCA(n_components=0.95) # Retain 95% of the variance
x_train_pca = pca.fit_transform(x_train_scaled)
x_test_pca = pca.transform(x_test_scaled)

print(f"Original training data shape: {x_train.shape}")
print(f"PCA transformed training data shape: {x_train_pca.shape}")
print(f"Original testing data shape: {x_test.shape}")
print(f"PCA transformed testing data shape: {x_test_pca.shape}")
print(f"Number of components selected by PCA: {pca.n_components_}")

"""### Visualizing PCA Results

Now, let's visualize the PCA-transformed data. We'll use the first two principal components to create a scatter plot. This can help us understand how the data points are distributed in the reduced-dimensional space and if there are any clear clusters, especially between fraudulent and non-fraudulent transactions.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Create a DataFrame for PCA results for easier plotting
pca_df = pd.DataFrame(data=x_train_pca[:, :2], columns=['Principal Component 1', 'Principal Component 2'])
pca_df['is_fraud'] = y_train.values # Add the target variable

plt.figure(figsize=(10, 8))
sns.scatterplot(
    x='Principal Component 1',
    y='Principal Component 2',
    hue='is_fraud',
    data=pca_df,
    palette='viridis',
    alpha=0.7
)
plt.title('PCA of Credit Card Transactions (First Two Principal Components)')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.grid(True)
plt.show()