# -*- coding: utf-8 -*-
"""ann(modified).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cGZEFOhLeVSjZhS4n_urfLLC-Sz3qdNN
"""

import numpy as np
import pandas as pd
from keras.models import Sequential
import warnings
warnings.filterwarnings("ignore")
from keras.layers import Dense
!pip install scikeras
from scikeras.wrappers import KerasClassifier

diabetes_data=pd.read_csv("diabetes.csv")
diabetes_data.head()

x=diabetes_data.drop(columns="Outcome")
y=diabetes_data["Outcome"]

#model creation
def my_model():
  model=Sequential()
  model.add(Dense(12,input_dim=8,activation="relu"))
  model.add(Dense(4,activation="sigmoid"))
  model.add(Dense(1,activation="sigmoid"))
  # Changed to 1 output unit for binary classification
  #compilation of model
  model.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])
  return model

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

model=my_model()
history=model.fit(x_train,y_train,epochs=50,batch_size=10,validation_split=0.2,verbose=1)

loss, accuracy = model.evaluate(x_test, y_test, verbose=1)
print(f"Test Accuracy: {accuracy:.4f}")

y_pred_prob = model.predict(x_test)
y_pred = (y_pred_prob > 0.5).astype(int)

print("Predicted values (0 or 1):", y_pred[:10].flatten())
print("Actual values:", y_test[:10])