# -*- coding: utf-8 -*-
"""biobert.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LkNfImwU6TvhKtPyFETY4u-CPDwT_Tqu
"""

pip install transformers torch

from transformers import AutoTokenizer, AutoModelForTokenClassification, pipeline

model_name="d4data/biomedical-ner-all"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForTokenClassification.from_pretrained(model_name)

ner =pipeline("ner",model=model,tokenizer=tokenizer,aggregation_strategy="simple")

text=input("Enter text here:")
results=ner(text)

for result in results:
  print(result)

for result in results:
  print(
      result['word'],
      "->",
      result["entity_group"],
      "->",
      round(result["score"],3)

  )