# -*- coding: utf-8 -*-
"""Chatbot_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lX3jXZbeTHl46Or349AoA3i2grSsQgzz
"""

!pip install transformers torch gradio
from transformers import AutoTokenizer, AutoModelForCausalLM
import gradio as gr
import torch

import gradio as gr
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

# 1.5B Instruct model with strong reasoning & factual ability
model_name = "Qwen/Qwen2.5-1.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)
device = "cuda" if torch.cuda.is_available() else "cpu"

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
    device_map="auto" if torch.cuda.is_available() else None,
)
if device == "cpu":
    model.to("cpu")


def chat(message):
    messages = [
        {
            "role": "system",
            "content": "You are a helpful, accurate, and concise assistant.",
        },
        {"role": "user", "content": message},
    ]

    # Apply the model's standard chat template
    text = tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    model_inputs = tokenizer([text], return_tensors="pt").to(device)

    with torch.no_grad():
        generated_ids = model.generate(
            **model_inputs,
            max_new_tokens=256,
            do_sample=False,  # Greedy decoding gives the most deterministic/accurate answers
        )

    # Slice out only the new tokens
    generated_ids = [
        output_ids[len(input_ids) :]
        for input_ids, output_ids in zip(
            model_inputs.input_ids, generated_ids
        )
    ]
    response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[
        0
    ]

    return response


demo = gr.Interface(
    fn=chat,
    inputs=gr.Textbox(label="Ask a question"),
    outputs=gr.Textbox(label="Answer"),
    title="AI Assistant",
)

demo.launch()