# -*- coding: utf-8 -*-
"""cnn_advanced_ai_ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yiik-bndrDwK_4l17sTltxN4dJ5viPuQ
"""

import zipfile
import os

with zipfile.ZipFile('/content/LungXRays-grayscale.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/Four_Classes')
print("Extraction completed")

print("COVID / Pneumonia / Tuberculosis / Normal dataset:")
print(os.listdir('/content/Four_Classes'))

base_dir = '/content/Four_Classes'
classes = os.listdir(os.path.join(base_dir, 'train')) # Assuming all splits have the same class directories

for split in ['train', 'val', 'test']:
    print("\n", split.upper())

    for class_name in classes:
        folder = os.path.join(base_dir, split, class_name)

        count = len([
            f for f in os.listdir(folder)
            if f.lower().endswith(('.jpg', '.jpeg', '.png'))
        ])

        print(class_name, ":", count)

train_dir = "/content/Four_Classes/train"
validation_dir = "/content/Four_Classes/val"
test_dir = "/content/Four_Classes/test"

IMG_SIZE = (128, 128)
BATCH_SIZE = 32
NUM_CLASSES = 4

import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt

train_ds = tf.keras.utils.image_dataset_from_directory(
    train_dir,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode="categorical"
)

validation_ds = tf.keras.utils.image_dataset_from_directory(
    validation_dir,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode="categorical"
)

test_ds = tf.keras.utils.image_dataset_from_directory(
    test_dir,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode="categorical",
    shuffle=False
)

print("Classes:", train_ds.class_names)

model = models.Sequential([

    # Input + Normalization
    layers.Input(shape=(128, 128, 3)),
    layers.Rescaling(1./255),

    # First CNN block
    layers.Conv2D(32, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    # Second CNN block
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    # Third CNN block
    layers.Conv2D(128, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    # Classification
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),

    # 4 classes
    layers.Dense(NUM_CLASSES, activation='softmax')
])

model.summary()

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    train_ds,
    validation_data=validation_ds,
    epochs=20
)

test_loss, test_accuracy = model.evaluate(test_ds)

print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)

# --------------------------------------------------
# 10. Plot accuracy
# --------------------------------------------------

plt.figure(figsize=(8, 5))

plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')

plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.title('Training and Validation Accuracy')
plt.legend()
plt.show()

# --------------------------------------------------
# 11. Plot loss
# --------------------------------------------------

plt.figure(figsize=(8, 5))

plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')

plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Training and Validation Loss')
plt.legend()
plt.show()

# --------------------------------------------------
# 12. Predictions on test data
# --------------------------------------------------

import numpy as np
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns

y_true = []
y_pred = []

for images, labels in test_ds:

    predictions = model.predict(images, verbose=0)

    y_true.extend(np.argmax(labels.numpy(), axis=1))
    y_pred.extend(np.argmax(predictions, axis=1))

# Class names
class_names = test_ds.class_names

print("Classes:", class_names)

# --------------------------------------------------
# 13. Confusion Matrix
# --------------------------------------------------

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(7, 6))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    xticklabels=class_names,
    yticklabels=class_names
)

plt.xlabel('Predicted Class')
plt.ylabel('Actual Class')
plt.title('Confusion Matrix')
plt.show()

# --------------------------------------------------
# 14. Classification Report
# --------------------------------------------------

print(
    classification_report(
        y_true,
        y_pred,
        target_names=class_names
    )
)