# -*- coding: utf-8 -*-
"""Logistic_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Ff9mz93utqNN5V0vkv_vW0apl5VI9gi
"""

import pandas as pd
import numpy as np

df=pd.read_csv("/content/Cancer_Data.csv")

df.head()

"""# Drop unnecessary columns"""

df = df.drop(columns=["id", "Unnamed: 32"], errors="ignore")

# Encode target: M=0 (malignant), B=1 (benign)
df["diagnosis"] = df["diagnosis"].map({"M": 0, "B": 1})

df.head()

df.tail()

df.shape

df.isnull().sum()

y=df['diagnosis']
y

x=df.drop(['diagnosis'],axis=1)

x

x

y.shape

x.shape

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.25,random_state=40)

x_test.shape

from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()

classifier.fit(x_train,y_train)

y_pred=classifier.predict(x_test)

y_pred

classifier.predict(x_test.iloc[1].values.reshape(1,30))

"""how the above code works"""

import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, 30, 35, 40],
    "City": ["NY", "LA", "Chicago", "Houston"]
}

df = pd.DataFrame(data)
print(df)

df.iloc[1]     # first row

df.iloc[2]     # third row

#Select row + column by position
df.iloc[1, 0]   # row 1, column 0 → "Bob"
df.iloc[2, 1]   # row 2, column 1 → 35

df.iloc[0:2]   # rows 0 and 1

df.iloc[0:2, 0:2]   # rows 0-1, columns 0-1

#Accuracy score
from sklearn.metrics import accuracy_score,classification_report

score=accuracy_score(y_pred,y_test)
print(score)

print(classification_report(y_pred,y_test))