# -*- coding: utf-8 -*-
"""Reading a dataframe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jY9UjQiCYKlcl1yeaHg9_GmKrhGqwuLx
"""

import pandas as pd

data_frame=pd.read_csv("/content/77_cancer_proteomes_CPTAC_itraq.csv")

data_frame.shape

data_frame.isnull()