# -*- coding: utf-8 -*-
"""text generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m7SyVPADRftuOhTA_aae7iNNvn8zOKK2
"""

!pip install transformers torch

from transformers import pipeline

generator=pipeline("text-generation",model="distilgpt2")

prompt=input("Enter your text: ")

result=generator(prompt,max_new_tokens=10,do_sample="T")

print(result[0],["generated_text"])

