# -*- coding: utf-8 -*-
"""text summary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ULW1PzWkNp3F5OQI0Aw9KfRaUIvUOEhY
"""

pip install -U transformers torch sentencepiece

pip install torchvision

from transformers import pipeline

summarizer=pipeline("summarization",model="facebook/bart-large-cnn")

text=""" DNA is the genetic material in living organisms. It stores genetic information and passes it from parents to offspring.DNA is made of 4 bases:A,T,G and C."""

summary = summarizer(text,max_length=30,min_length=10,do_sample=False)

print("Summary:")

print(summary[0]["summary_text"])